image:
  file: .gitpod.Dockerfile
tasks:
  - name: rabbitmq
    init: mkdir -p /workspace/data
    command: docker-compose -f docker-compose-rabbit.yaml up
  - name: localstack
    init: mkdir -p /workspace/data
    command: docker-compose -f docker-compose-localstack.yaml up
  - name: redis
    command: redis-server
  - name: MockServer
    init: npm i
    command: node mock-server.js
ports:
  - port: 5672
    onOpen: ignore
  - port: 1080
    onOpen: ignore
  - port: 4566
    onOpen: ignore
  - port: 4571
    onOpen: ignore
  - port: 3306
    onOpen: ignore
