tasks:
  - name: rabbitmq
    init: mkdir -p /workspace/data
    command: docker-compose up
  - name: MockServer
    init: npm i
    command: node mock-server.js
ports:
  - port: 5672
    onOpen: ignore
  - port: 1080
    onOpen: ignore
  - port: 4566
    onOpen: ignore
  - port: 4571
    onOpen: ignore
