image:
  file: .gitpod.Dockerfile
tasks:
  - name: rabbitmq
    init: mkdir -p /workspace/data
    command: docker-compose -f docker-compose-rabbit.yaml up
  - name: localstack
    init: mkdir -p /workspace/data
    command: docker-compose -f docker-compose-localstack.yaml up
  - name: redis
    command: redis-server
  - name: MockServer
    init: npm i
    command: node mock-server.js
  - name: ExampleFlow
    init: npm i
    command: echo "Sleep 10s";sleep 10; ./lambdatest.sh
  
ports:
  - port: 5672 
    onOpen: ignore
  - port: 1080 
    onOpen: ignore
  - port: 4566 
    onOpen: ignore
  - port: 4571 
    onOpen: ignore
  - port: 3306 
    onOpen: ignore
  - port: 6379 
    onOpen: ignore

hosts:
  staging.lambda.mydomain.com : 127.0.0.1
  production.lambda.mydomain.com : 127.0.0.1
  service-ext1.mydomain.com : 127.0.0.1
  service-ext2.mydomain.com : 127.0.0.1
  
vscode:
  extensions:
    - golang.Go
    - cweijan.vscode-mysql-client2
    - humao.rest-client