image:
  file: .gitpod.Dockerfile
tasks:
  - name: rabbitmq
    init: mkdir -p /workspace/data
    command: docker-compose -f docker-compose-rabbit.yaml up
  - name: localstack
    init: mkdir -p /workspace/data
    command: docker-compose -f docker-compose-localstack.yaml up
  - name: redis
    command: redis-server
  - name: MockServer
    init: npm i
    command: node mock-server.js
ports:
  - port: 5672 # Rabbit
  - port: 1080 # Mock-server
  - port: 4566 # local-stack
  - port: 4571 # local-stack
  - port: 3306 # mysql
  - port: 6379 # redis
    onOpen: ignore
