version: "3"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      - SERVICES=${SERVICES-lambda,apigateway,dynamodb,dynamodbstreams,s3,s3api,secretsmanager,ses,sns,sqs }
      - DEBUG=1
      - DATA_DIR=${DATA_DIR-/tmp/localstack/data}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-local }
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock

    volumes:
      - "${TMP_DIR:-/workspace/data}:${TMP_DIR:-/tmp/localstack}" # used for LocalStack internal data
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-network

networks:
  localstack-network:
    name: localstack-network
    driver: bridge
